const GACHI_DATA = [
  {
    "category": "videos",
    "items": [
      {"name": "(Lion King) Can you Feel the Love Tonight - Right Version", "path": "Z:/гачибасс/GachiBassRadioV2/(Lion King) Can you Feel the Love Tonight - Right Version.mp4"},
      {"name": "Alice C♂♂per - Poison (Masculine♂Mix)", "path": "Z:/гачибасс/GachiBassRadioV2/Alice C♂♂per - Poison (Masculine♂Mix).mp4"},
      {"name": "Ariana Grande - Break Free (Gay♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Ariana Grande - Break Free (Gay♂Version).mp4"},
      {"name": "Dr.Disrespect - Gillette (Right Version ♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Dr.Disrespect - Gillette (Right Version ♂).mp4"},
      {"name": "Gachi 24k ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Gachi 24k ♂.mp4"},
      {"name": "Gachi Back ♂ feat. Vermicelli", "path": "Z:/гачибасс/GachiBassRadioV2/Gachi Back ♂ feat. Vermicelli.mp4"},
      {"name": "Gachi no 5", "path": "Z:/гачибасс/GachiBassRadioV2/Gachi no 5.mp4"},
      {"name": "Gachimuchi - Strength of a Thousand Men -Two Steps from Hell", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Strength of a Thousand Men -Two Steps from Hell.mp4"},
      {"name": "Gachirocker", "path": "Z:/гачибасс/GachiBassRadioV2/Gachirocker.mp4"},
      {"name": "Haddagay What Is Slave", "path": "Z:/гачибасс/GachiBassRadioV2/Haddagay What Is Slave.mp4"},
      {"name": "HandsUp CMON MAN HandsUp", "path": "Z:/гачибасс/GachiBassRadioV2/HandsUp CMON MAN HandsUp.mp4"},
      {"name": "Happy (Right ♂ Version ♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Happy (Right ♂ Version ♂).mp4"},
      {"name": "I Need Your Love (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/I Need Your Love (Right♂Version).mp4"},
      {"name": "I ♂ FOLLOW ♂ GACHI", "path": "Z:/гачибасс/GachiBassRadioV2/I ♂ FOLLOW ♂ GACHI.mp4"},
      {"name": "Jellyfish Jam ♂Right Version♂", "path": "Z:/гачибасс/GachiBassRadioV2/Jellyfish Jam ♂Right Version♂.mp4"},
      {"name": "Kappa Shorts ♂ GACHI ♂ DOCTOR ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Kappa Shorts ♂ GACHI ♂ DOCTOR ♂.mp4"},
      {"name": "Knife Party _ Tom Morello - Battle Sirens (RIOT Remix) (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Knife Party _ Tom Morello - Battle Sirens (RIOT Remix) (Right♂Version).mp4"},
      {"name": "Krewella - Surrender The Throne (Right♂ Version♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Krewella - Surrender The Throne (Right♂ Version♂).mp4"},
      {"name": "Lazy Dungeon - Cooking by the book (right♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/Lazy Dungeon - Cooking by the book (right♂version).mp4"},
      {"name": "Lean on ♂ [RIGHT VERSION] ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Lean on ♂ [RIGHT VERSION] ♂.mp4"},
      {"name": "Let Me Think About It (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Let Me Think About It (Right♂Version).mp4"},
      {"name": "Lights Out (Gachimuchi version)  Van CancerHolme", "path": "Z:/гачибасс/GachiBassRadioV2/Lights Out (Gachimuchi version)  Van CancerHolme.mp4"},
      {"name": "Lil Gay - Gachi Gang (RIGHT VERSION) RIP BILLY", "path": "Z:/гачибасс/GachiBassRadioV2/Lil Gay - Gachi Gang (RIGHT VERSION) RIP BILLY.mp4"},
      {"name": "Love V.A.N. [Audio Only]", "path": "Z:/гачибасс/GachiBassRadioV2/Love V.A.N. [Audio Only].mp4"},
      {"name": "Meme Meme Meme (Serebro cancer gachi remix)", "path": "Z:/гачибасс/GachiBassRadioV2/Meme Meme Meme (Serebro cancer gachi remix).mp4"},
      {"name": "Miley Cyrus - Wrecking Ball (Uncensored♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/Miley Cyrus - Wrecking Ball (Uncensored♂version).mp4"},
      {"name": "My Only Dungeon", "path": "Z:/гачибасс/GachiBassRadioV2/My Only Dungeon.mp4"},
      {"name": "M♂dern Talking - Y♂u_re My Heart, Y♂u_re My S♂ul (Right Version♂)", "path": "Z:/гачибасс/GachiBassRadioV2/M♂dern Talking - Y♂u_re My Heart, Y♂u_re My S♂ul (Right Version♂).mp4"},
      {"name": "One Republic - Connection (Uncensored♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/One Republic - Connection (Uncensored♂version).mp4"},
      {"name": "PEWDIEPIE -♂BITCH LASAGNA♂right version♂(gachi)♂", "path": "Z:/гачибасс/GachiBassRadioV2/PEWDIEPIE -♂BITCH LASAGNA♂right version♂(gachi)♂.mp4"},
      {"name": "PROJECT Gachimuchi  Van CancerHolme", "path": "Z:/гачибасс/GachiBassRadioV2/PROJECT Gachimuchi  Van CancerHolme.mp4"},
      {"name": "Pigeon John - The Bomb (right♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/Pigeon John - The Bomb (right♂version).mp4"},
      {"name": "Platinum♂Disco", "path": "Z:/гачибасс/GachiBassRadioV2/Platinum♂Disco.mp4"},
      {"name": "Propane Nightmares (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Propane Nightmares (Right♂Version).mp4"},
      {"name": "Queen - We are the champions (proper♂tribute)", "path": "Z:/гачибасс/GachiBassRadioV2/Queen - We are the champions (proper♂tribute).mp4"},
      {"name": "Rule 69 - If it exists there is gachi of it", "path": "Z:/гачибасс/GachiBassRadioV2/Rule 69 - If it exists there is gachi of it.mp4"},
      {"name": "Running ♂ Away", "path": "Z:/гачибасс/GachiBassRadioV2/Running ♂ Away.mp4"},
      {"name": "SUPER ♂ GACHI ♂ SAIYAN", "path": "Z:/гачибасс/GachiBassRadioV2/SUPER ♂ GACHI ♂ SAIYAN.mp4"},
      {"name": "Self Control", "path": "Z:/гачибасс/GachiBassRadioV2/Self Control.mp4"},
      {"name": "Sia - Chandelier (Alternative♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Sia - Chandelier (Alternative♂Version).mp4"},
      {"name": "Smooth♂Boy♂Next♂Door", "path": "Z:/гачибасс/GachiBassRadioV2/Smooth♂Boy♂Next♂Door.mp4"},
      {"name": "Sound of thunder", "path": "Z:/гачибасс/GachiBassRadioV2/Sound of thunder.mp4"},
      {"name": "Spankau Ballet - G♂ld", "path": "Z:/гачибасс/GachiBassRadioV2/Spankau Ballet - G♂ld.mp4"},
      {"name": "Stay High ♂ [RIGHT VERSION] ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Stay High ♂ [RIGHT VERSION] ♂.mp4"},
      {"name": "Stereo Sans Rave - Mashup [Aniko ♂Release♂]", "path": "Z:/гачибасс/GachiBassRadioV2/Stereo Sans Rave - Mashup [Aniko ♂Release♂].mp4"},
      {"name": "Stonebank - ♂ Strength is CUMMING ♂ [MASHUP]", "path": "Z:/гачибасс/GachiBassRadioV2/Stonebank - ♂ Strength is CUMMING ♂ [MASHUP].mp4"},
      {"name": "THIS♂IS♂A♂DUNGEON♂MASTER", "path": "Z:/гачибасс/GachiBassRadioV2/THIS♂IS♂A♂DUNGEON♂MASTER.mp4"},
      {"name": "Taylor Swift ♂ Spank It Off (♂ Right Version ♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Taylor Swift ♂ Spank It Off (♂ Right Version ♂).mp4"},
      {"name": "Techno Synth", "path": "Z:/гачибасс/GachiBassRadioV2/Techno Synth.mp4"},
      {"name": "The Gachiberries ♂ Zombie ♂ Gachimuchi", "path": "Z:/гачибасс/GachiBassRadioV2/The Gachiberries ♂ Zombie ♂ Gachimuchi.mp4"},
      {"name": "Trance - 69 Dungeon System Dreamscape", "path": "Z:/гачибасс/GachiBassRadioV2/Trance - 69 Dungeon System Dreamscape.mp4"},
      {"name": "Uptown Gachi Mix", "path": "Z:/гачибасс/GachiBassRadioV2/Uptown Gachi Mix.mp4"},
      {"name": "Van CancerHolme  Childish Aniki", "path": "Z:/гачибасс/GachiBassRadioV2/Van CancerHolme  Childish Aniki.mp4"},
      {"name": "Van Darkholme - Death to all slaves", "path": "Z:/гачибасс/GachiBassRadioV2/Van Darkholme - Death to all slaves.mp4"},
      {"name": "Van Darkholmes Floral Penis [GAYP♂RWAVE] Short Version", "path": "Z:/гачибасс/GachiBassRadioV2/Van Darkholmes Floral Penis [GAYP♂RWAVE] Short Version.mp4"},
      {"name": "Van Trumpholme - Every time we touch", "path": "Z:/гачибасс/GachiBassRadioV2/Van Trumpholme - Every time we touch.mp4"},
      {"name": "Vengab♂ys - Spank, Spank, Spank, Spank!!", "path": "Z:/гачибасс/GachiBassRadioV2/Vengab♂ys - Spank, Spank, Spank, Spank!!.mp4"},
      {"name": "Venus (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Venus (Right♂Version).mp4"},
      {"name": "We are two blocks down", "path": "Z:/гачибасс/GachiBassRadioV2/We are two blocks down.mp4"},
      {"name": "Wicked Game - ♂ Right Version ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Wicked Game - ♂ Right Version ♂.mp4"},
      {"name": "Witchcraft (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Witchcraft (Right♂Version).mp4"},
      {"name": "Wiz Khalifa ft. Charlie Puth - See You Again (right♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/Wiz Khalifa ft. Charlie Puth - See You Again (right♂version).mp4"},
      {"name": "Wrestling Train - Shake up ♂Leatherman♂", "path": "Z:/гачибасс/GachiBassRadioV2/Wrestling Train - Shake up ♂Leatherman♂.mp4"},
      {"name": "You Spin (Fist) Me Round", "path": "Z:/гачибасс/GachiBassRadioV2/You Spin (Fist) Me Round.mp4"},
      {"name": "[GACHIMUCHI] NOVIY ♂ GOD", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHIMUCHI] NOVIY ♂ GOD.mp4"},
      {"name": "♂ Avicii _ Billy - SOS (slaves) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Avicii _ Billy - SOS (slaves) ♂.mp4"},
      {"name": "♂ BELIVIER - TRUE GACHIMUCHI EDITION ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ BELIVIER - TRUE GACHIMUCHI EDITION ♂.mp4"},
      {"name": "♂ Billy-Fly ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Billy-Fly ♂.mp4"},
      {"name": "♂ Dont stop cumming ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Dont stop cumming ♂.mp4"},
      {"name": "♂ Drop it like its Hot (Right Version) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Drop it like its Hot (Right Version) ♂.mp4"},
      {"name": "♂ Dungeon Police ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Dungeon Police ♂.mp4"},
      {"name": "♂ Everybody Wants to Make Me Cum ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Everybody Wants to Make Me Cum ♂.mp4"},
      {"name": "♂ FUNKYTOWN ♂ GACHIMUCHI ♂ EDITION ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ FUNKYTOWN ♂ GACHIMUCHI ♂ EDITION ♂.mp4"},
      {"name": "♂ Feint - Slave Eyes ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Feint - Slave Eyes ♂.mp4"},
      {"name": "♂ Feint - Slave ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Feint - Slave ♂.mp4"},
      {"name": "♂ Fisting Park - Crawling ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Fisting Park - Crawling ♂.mp4"},
      {"name": "♂ G-Type Life ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ G-Type Life ♂.mp4"},
      {"name": "♂ GACHIBANK - THE SUCTION ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ GACHIBANK - THE SUCTION ♂.mp4"},
      {"name": "♂ GLEE - DUNGEON BOY FUCK (FISTMAS SPECIAL 2017) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ GLEE - DUNGEON BOY FUCK (FISTMAS SPECIAL 2017) ♂.mp4"},
      {"name": "♂ Gachi Heaven _ EH!DE - My Ass ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachi Heaven _ EH!DE - My Ass ♂.mp4"},
      {"name": "♂ Gachicito ♂ (versión correcta)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachicito ♂ (versión correcta).mp4"},
      {"name": "♂ Gachizilla ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachizilla ♂.mp4"},
      {"name": "♂ Gachophone ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachophone ♂.mp4"},
      {"name": "♂ Galantass - Runaway ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Galantass - Runaway ♂.mp4"},
      {"name": "♂ Gaynther - Ding Dong Song ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gaynther - Ding Dong Song ♂.mp4"},
      {"name": "♂ HB - S3X (FEAT. VAN DARKHOLME) (LYRIC VIDEO) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ HB - S3X (FEAT. VAN DARKHOLME) (LYRIC VIDEO) ♂.mp4"},
      {"name": "♂ I can Take [it, Boy] ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ I can Take [it, Boy] ♂.mp4"},
      {"name": "♂ IMAGINE DRAGONS - BATTLE ( ♂ GAY ♂ ) CRY ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ IMAGINE DRAGONS - BATTLE ( ♂ GAY ♂ ) CRY ♂.mp4"},
      {"name": "♂ INFINITY ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ INFINITY ♂.mp4"},
      {"name": "♂ Ill be there fuck you ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Ill be there fuck you ♂.mp4"},
      {"name": "♂ Imagine Dungeons - Radioactive ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Imagine Dungeons - Radioactive ♂.mp4"},
      {"name": "♂ Initial D ♂ Remember Me ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Initial D ♂ Remember Me ♂.mp4"},
      {"name": "♂ Its raining Van ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Its raining Van ♂.mp4"},
      {"name": "♂ Jizzie J - Fucking Slaves ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Jizzie J - Fucking Slaves ♂.mp4"},
      {"name": "♂ Leave the Gachimuchi on ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Leave the Gachimuchi on ♂.mp4"},
      {"name": "♂ Marina And The Diamonds - Lonely Slaves Club ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Marina And The Diamonds - Lonely Slaves Club ♂.mp4"},
      {"name": "♂ OutKast - How Ya Like ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ OutKast - How Ya Like ♂.mp4"},
      {"name": "♂ Plug In Billy ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Plug In Billy ♂.mp4"},
      {"name": "♂ Pumped Up Dicks ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Pumped Up Dicks ♂.mp4"},
      {"name": "♂ Push it To the Limit ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Push it To the Limit ♂.mp4"},
      {"name": "♂ Rameses D - Memoirs ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Rameses D - Memoirs ♂.mp4"},
      {"name": "♂ Right Here, Right Now (Right Version) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Right Here, Right Now (Right Version) ♂.mp4"},
      {"name": "♂ SPANK THE MOON - Shut Up and Fuck ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ SPANK THE MOON - Shut Up and Fuck ♂.mp4"},
      {"name": "♂ SUGAR - RIGHT VERSION ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ SUGAR - RIGHT VERSION ♂.mp4"},
      {"name": "♂ Slave Power ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Slave Power ♂.mp4"},
      {"name": "♂ Slipknot - Duality ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Slipknot - Duality ♂.mp4"},
      {"name": "♂ Stereo Love ♂ (Gachi Edit)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Stereo Love ♂ (Gachi Edit).mp4"},
      {"name": "♂ Stonebank - How strong you are ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Stonebank - How strong you are ♂.mp4"},
      {"name": "♂ Stonespank - Whos Got Your Ass ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Stonespank - Whos Got Your Ass ♂.mp4"},
      {"name": "♂ Stormzy - Shut Up ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Stormzy - Shut Up ♂.mp4"},
      {"name": "♂ The Real Dungeon Master ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ The Real Dungeon Master ♂.mp4"},
      {"name": "♂ The Slaves - Mr. Suction ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ The Slaves - Mr. Suction ♂.mp4"},
      {"name": "♂ VANGAGAYS - UHUHUH UHUH (GACHICAL ASSNESS) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VANGAGAYS - UHUHUH UHUH (GACHICAL ASSNESS) ♂.mp4"},
      {"name": "♂ VANGAGAYS - WE LIKE TO GACHI! (THE GACHIBUS) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VANGAGAYS - WE LIKE TO GACHI! (THE GACHIBUS) ♂.mp4"},
      {"name": "♂ Vamposaur Gachi Tutorial ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Vamposaur Gachi Tutorial ♂.mp4"},
      {"name": "♂️ AssClap ♂️ (Right version) REUPLOAD", "path": "Z:/гачибасс/GachiBassRadioV2/♂️ AssClap ♂️ (Right version) REUPLOAD.mp4"},
      {"name": "♂️ Redbone ♂️ (Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/♂️ Redbone ♂️ (Right Version).mp4"},
      {"name": "♂️ ФРЕНДЗОНА ⧸ МЭЙБИ БЭЙБИ — БУТЫЛОЧКА (Right Version) ♂️", "path": "Z:/гачибасс/GachiBassRadioV2/♂️ ФРЕНДЗОНА ⧸ МЭЙБИ БЭЙБИ — БУТЫЛОЧКА (Right Version) ♂️.mp4"},
      {"name": "♂️ Монеточка - Gachий Раз ♂ (TRedCat Gachi Remix) [Каждый раз]", "path": "Z:/гачибасс/GachiBassRadioV2/♂️ Монеточка - Gachий Раз ♂ (TRedCat Gachi Remix) [Каждый раз].mp4"},
      {"name": "Symphony No. 5 in C minor - Ludwig ♂VAN♂ Beethoven", "path": "Z:/гачибасс/GachiBassRadioV2/Symphony No. 5 in C minor - Ludwig ♂VAN♂ Beethoven.mp4"},
      {"name": "bg", "path": "Z:/гачибасс/GachiBassRadioV2/video/bg.mp4"},
      {"name": "billy", "path": "Z:/гачибасс/GachiBassRadioV2/video/billy.mp4"}
    ],
  },
  {
    "category": "tracks",
    "items": [
      {"name": "(Gachi Remix) Big Baby Tape - Gimme the Ass ♂", "path": "Z:/гачибасс/GachiBassRadioV2/(Gachi Remix) Big Baby Tape - Gimme the Ass ♂.mp3"},
      {"name": "(Titanic) My Heart Will Go On - Right Version - gachi", "path": "Z:/гачибасс/GachiBassRadioV2/(Titanic) My Heart Will Go On - Right Version - gachi.mp3"},
      {"name": "A Thousand AAAAAHs - VANessa Herrington", "path": "Z:/гачибасс/GachiBassRadioV2/A Thousand AAAAAHs - VANessa Herrington.mp3"},
      {"name": "Adam Lambert - Ghost Town (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Adam Lambert - Ghost Town (Right♂Version).mp3"},
      {"name": "Alan Walker - Alone Right Version ♂♂♂", "path": "Z:/гачибасс/GachiBassRadioV2/Alan Walker - Alone Right Version ♂♂♂.mp3"},
      {"name": "Alfucks - The♂Golden♂Showers", "path": "Z:/гачибасс/GachiBassRadioV2/Alfucks - The♂Golden♂Showers.mp3"},
      {"name": "Attack on Gachi ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Attack on Gachi ♂.mp3"},
      {"name": "BBilly BBerrington - ASSPUTIN ♂", "path": "Z:/гачибасс/GachiBassRadioV2/BBilly BBerrington - ASSPUTIN ♂.mp3"},
      {"name": "BBilly BBerrington - GACHI BEE ♂", "path": "Z:/гачибасс/GachiBassRadioV2/BBilly BBerrington - GACHI BEE ♂.mp3"},
      {"name": "BBilly BBerrington - VANCUTTA (SUCTION SUCTION SUCTION) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/BBilly BBerrington - VANCUTTA (SUCTION SUCTION SUCTION) ♂.mp3"},
      {"name": "BBilly BBerrington - ♂ HERRINGTONE I FUCK YOU♂", "path": "Z:/гачибасс/GachiBassRadioV2/BBilly BBerrington - ♂ HERRINGTONE I FUCK YOU♂.mp3"},
      {"name": "BBilly BBerrington - ♂ VANDULUM SEXDOWN ♂", "path": "Z:/гачибасс/GachiBassRadioV2/BBilly BBerrington - ♂ VANDULUM SEXDOWN ♂.mp3"},
      {"name": "Bad Apple feat. Aniki", "path": "Z:/гачибасс/GachiBassRadioV2/Bad Apple feat. Aniki.mp3"},
      {"name": "Bad♂Guy", "path": "Z:/гачибасс/GachiBassRadioV2/Bad♂Guy.mp3"},
      {"name": "Big Baby Tape - ♂surname♂ (gachimuchi версия)", "path": "Z:/гачибасс/GachiBassRadioV2/Big Baby Tape - ♂surname♂ (gachimuchi версия).mp3"},
      {"name": "Chainsmokers - #Selfie (right♂version)", "path": "Z:/гачибасс/GachiBassRadioV2/Chainsmokers - #Selfie (right♂version).mp3"},
      {"name": "Chemical Dungeon Zone", "path": "Z:/гачибасс/GachiBassRadioV2/Chemical Dungeon Zone.mp3"},
      {"name": "Cockarina Of Time ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Cockarina Of Time ♂.mp3"},
      {"name": "Cybergachi ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Cybergachi ♂.mp3"},
      {"name": "DEAMN - Save Me (Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/DEAMN - Save Me (Right Version).mp3"},
      {"name": "DJ ÜberGäy1488 - чёрные глаза (Right Version ♂)", "path": "Z:/гачибасс/GachiBassRadioV2/DJ ÜberGäy1488 - чёрные глаза (Right Version ♂).mp3"},
      {"name": "Darren Spanks Gachimer - Feel Like Slaves", "path": "Z:/гачибасс/GachiBassRadioV2/Darren Spanks Gachimer - Feel Like Slaves.mp3"},
      {"name": "DjCancerMancer - Need Gachi Right Now", "path": "Z:/гачибасс/GachiBassRadioV2/DjCancerMancer - Need Gachi Right Now.mp3"},
      {"name": "DjCancerMancer - ♂Rainbow Road♂", "path": "Z:/гачибасс/GachiBassRadioV2/DjCancerMancer - ♂Rainbow Road♂.mp3"},
      {"name": "Door 169 - Upper Floor of broken dreams", "path": "Z:/гачибасс/GachiBassRadioV2/Door 169 - Upper Floor of broken dreams.mp3"},
      {"name": "Dungeon 312 - Останусь [Right version Gachi Mix] - Город 312 - Останусь", "path": "Z:/гачибасс/GachiBassRadioV2/Dungeon 312 - Останусь [Right version Gachi Mix] - Город 312 - Останусь.mp3"},
      {"name": "Fire♂stone", "path": "Z:/гачибасс/GachiBassRadioV2/Fire♂stone.mp3"},
      {"name": "Frainbreeze (Right♂Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Frainbreeze (Right♂Version).mp3"},
      {"name": "GACHIBANK - BILL AUGHRIGHT", "path": "Z:/гачибасс/GachiBassRadioV2/GACHIBANK - BILL AUGHRIGHT.mp3"},
      {"name": "GACHIMUCHI - Ludwig ♂VAN♂ Beethoven", "path": "Z:/гачибасс/GachiBassRadioV2/GACHIMUCHI - Ludwig ♂VAN♂ Beethoven.mp3"},
      {"name": "Gachi - GAY♂ON♂ME♂", "path": "Z:/гачибасс/GachiBassRadioV2/Gachi - GAY♂ON♂ME♂.mp3"},
      {"name": "Gachi Polka", "path": "Z:/гачибасс/GachiBassRadioV2/Gachi Polka.mp3"},
      {"name": "Gachimuchi - A.D.V.A.N.C.E", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - A.D.V.A.N.C.E.mp3"},
      {"name": "Gachimuchi - Aniki ♂ Sunrise", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Aniki ♂ Sunrise.mp3"},
      {"name": "Gachimuchi - Cumbusters", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Cumbusters.mp3"},
      {"name": "Gachimuchi - Gay ♂ Party ♥", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Gay ♂ Party ♥.mp3"},
      {"name": "Gachimuchi - Get♂low", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Get♂low.mp3"},
      {"name": "Gachimuchi - Good time♂", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Good time♂.mp3"},
      {"name": "Gachimuchi - Pump it", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Pump it.mp3"},
      {"name": "Gachimuchi - Remember the VAN", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Remember the VAN.mp3"},
      {"name": "Gachimuchi - Sad♂Van", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Sad♂Van.mp3"},
      {"name": "Gachimuchi - Something Just♂Like This", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Something Just♂Like This.mp3"},
      {"name": "Gachimuchi - Song 2", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Song 2.mp3"},
      {"name": "Gachimuchi - Steins GAYte", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Steins GAYte.mp3"},
      {"name": "Gachimuchi - Sweet Dreams", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Sweet Dreams.mp3"},
      {"name": "Gachimuchi - That♂Boy", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - That♂Boy.mp3"},
      {"name": "Gachimuchi - The Tide", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - The Tide.mp3"},
      {"name": "Gachimuchi - Waiting for love", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi - Waiting for love.mp3"},
      {"name": "Gachimuchi Circulation", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi Circulation.mp3"},
      {"name": "Gachimuchi- Byoumei wa ai datta", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi- Byoumei wa ai datta.mp3"},
      {"name": "Gachimuchi- Obamiru", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi- Obamiru.mp3"},
      {"name": "Gachimuchi- Orange Sapphire", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi- Orange Sapphire.mp3"},
      {"name": "Gachimuchi- 世界♂中心", "path": "Z:/гачибасс/GachiBassRadioV2/Gachimuchi- 世界♂中心.mp3"},
      {"name": "JoJo Golden Wind  ♂️ Secret Opening ♂️", "path": "Z:/гачибасс/GachiBassRadioV2/JoJo Golden Wind  ♂️ Secret Opening ♂️.mp3"},
      {"name": "Kenitek- ♂ Van Darkholme Loves Sexting! ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Kenitek- ♂ Van Darkholme Loves Sexting! ♂.mp3"},
      {"name": "LITTLE ♂BIG♂ - I_m ok (Gachi remix by TRedCat)", "path": "Z:/гачибасс/GachiBassRadioV2/LITTLE ♂BIG♂ - I_m ok (Gachi remix by TRedCat).mp3"},
      {"name": "Linkin Park - What I_ve Done (LP Gachi Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Linkin Park - What I_ve Done (LP Gachi Right Version).mp3"},
      {"name": "LiteraryRevival reupload", "path": "Z:/гачибасс/GachiBassRadioV2/LiteraryRevival reupload.mp3"},
      {"name": "No Gayme No Life [Gachimuchi ver.]", "path": "Z:/гачибасс/GachiBassRadioV2/No Gayme No Life [Gachimuchi ver.].mp3"},
      {"name": "Omae Wa Mou _ Gachimuchi Ver.", "path": "Z:/гачибасс/GachiBassRadioV2/Omae Wa Mou _ Gachimuchi Ver..mp3"},
      {"name": "RASA - Dickовод (Пчеловод right version) gachi remix", "path": "Z:/гачибасс/GachiBassRadioV2/RASA - Dickовод (Пчеловод right version) gachi remix.mp3"},
      {"name": "Rather♂Be", "path": "Z:/гачибасс/GachiBassRadioV2/Rather♂Be.mp3"},
      {"name": "Silent Circle - T♂uch In The Night (Right Version♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Silent Circle - T♂uch In The Night (Right Version♂).mp3"},
      {"name": "Smash Anus - Gym Stars (Smash Mouth - All Star Gachi right version)", "path": "Z:/гачибасс/GachiBassRadioV2/Smash Anus - Gym Stars (Smash Mouth - All Star Gachi right version).mp3"},
      {"name": "Spinnin♂Records", "path": "Z:/гачибасс/GachiBassRadioV2/Spinnin♂Records.mp3"},
      {"name": "Stefán Karl Stefánsson - WE ARE NUMBER 69 (We Are Number One Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Stefán Karl Stefánsson - WE ARE NUMBER 69 (We Are Number One Right Version).mp3"},
      {"name": "The Prototypes - Hyperslave", "path": "Z:/гачибасс/GachiBassRadioV2/The Prototypes - Hyperslave.mp3"},
      {"name": "TiK♂ToK", "path": "Z:/гачибасс/GachiBassRadioV2/TiK♂ToK.mp3"},
      {"name": "Van Darkholme - Death to all slaves", "path": "Z:/гачибасс/GachiBassRadioV2/Van Darkholme - Death to all slaves.mp3"},
      {"name": "Van Darkholme feat  Gachigasm   Dont be so deep  ", "path": "Z:/гачибасс/GachiBassRadioV2/Van Darkholme feat  Gachigasm   Dont be so deep  .mp3"},
      {"name": "XXX-Coast - Gachi Bay ♂", "path": "Z:/гачибасс/GachiBassRadioV2/XXX-Coast - Gachi Bay ♂.mp3"},
      {"name": "[GACHIMUCHI] TAKE  ON  VAN", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHIMUCHI] TAKE  ON  VAN.mp3"},
      {"name": "[GACHIMUCHI] ♂BOYFIRE♂", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHIMUCHI] ♂BOYFIRE♂.mp3"},
      {"name": "[GACHISHORTS #1] ♂ DUNGEONVANIA - VANPIRE KILLER ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHISHORTS #1] ♂ DUNGEONVANIA - VANPIRE KILLER ♂.mp3"},
      {"name": "[GACHISHORTS #2] ♂ ANIKI - GAYGAYGAYGAY ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHISHORTS #2] ♂ ANIKI - GAYGAYGAYGAY ♂.mp3"},
      {"name": "[GACHISHORTS #3] ♂ DEAD OR ANIKI - YOU SPANK ME ROUND (LIKE A MASTER) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHISHORTS #3] ♂ DEAD OR ANIKI - YOU SPANK ME ROUND (LIKE A MASTER) ♂.mp3"},
      {"name": "[GACHISHORTS #4] ♂ V4N - HYPNOCOCK ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[GACHISHORTS #4] ♂ V4N - HYPNOCOCK ♂.mp3"},
      {"name": "[Gachimuchi] ♂ Mr SandMaN ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[Gachimuchi] ♂ Mr SandMaN ♂.mp3"},
      {"name": "[gachimuchi] Gaytama ♂", "path": "Z:/гачибасс/GachiBassRadioV2/[gachimuchi] Gaytama ♂.mp3"},
      {"name": "[gachimuchi] Half Moon Serenade", "path": "Z:/гачибасс/GachiBassRadioV2/[gachimuchi] Half Moon Serenade.mp3"},
      {"name": "_МЭЙБИ БЭЙБИ — БУТЫЛОЧКА (Right Version) ♂️", "path": "Z:/гачибасс/GachiBassRadioV2/_МЭЙБИ БЭЙБИ — БУТЫЛОЧКА (Right Version) ♂️.mp3"},
      {"name": "_Тима белорусских Витаминка gachi remix", "path": "Z:/гачибасс/GachiBassRadioV2/_Тима белорусских Витаминка gachi remix.mp3"},
      {"name": "duyui - ♂ Its so Its so Its so ♂", "path": "Z:/гачибасс/GachiBassRadioV2/duyui - ♂ Its so Its so Its so ♂.mp3"},
      {"name": "gachi - От винта", "path": "Z:/гачибасс/GachiBassRadioV2/gachi - От винта.mp3"},
      {"name": "t.A.T.u. - Мальчик GAY♂", "path": "Z:/гачибасс/GachiBassRadioV2/t.A.T.u. - Мальчик GAY♂.mp3"},
      {"name": "xelivad - ky♂t♂", "path": "Z:/гачибасс/GachiBassRadioV2/xelivad - ky♂t♂.mp3"},
      {"name": "Акула - Кислтный DJ (Right version)Gachi Remix", "path": "Z:/гачибасс/GachiBassRadioV2/Акула - Кислтный DJ (Right version)Gachi Remix.mp3"},
      {"name": "Артур Пирожков - Fucking slaveичка (Gachimuchi Артур Пирожков - Алкоголичка remix)", "path": "Z:/гачибасс/GachiBassRadioV2/Артур Пирожков - Fucking slaveичка (Gachimuchi Артур Пирожков - Алкоголичка remix).mp3"},
      {"name": "Артур Пирожков - Gachiпила (_Зацепила_ gachi remix)", "path": "Z:/гачибасс/GachiBassRadioV2/Артур Пирожков - Gachiпила (_Зацепила_ gachi remix).mp3"},
      {"name": "Беспечный ♂ Master ♂", "path": "Z:/гачибасс/GachiBassRadioV2/Беспечный ♂ Master ♂.mp3"},
      {"name": "Бутырка - ♂АААттестат♂ (Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Бутырка - ♂АААттестат♂ (Right Version).mp3"},
      {"name": "Бутырка - ♂Шарик♂ (Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Бутырка - ♂Шарик♂ (Right Version).mp3"},
      {"name": "Валентин Стрыкало - Наш Dungeon Master(Gachi Remix, GachiBass)", "path": "Z:/гачибасс/GachiBassRadioV2/Валентин Стрыкало - Наш Dungeon Master(Gachi Remix, GachiBass).mp3"},
      {"name": "Верка Сердючка - Гуляночка (right version) G man", "path": "Z:/гачибасс/GachiBassRadioV2/Верка Сердючка - Гуляночка (right version) G man.mp3"},
      {"name": "Вирус - Ну где же ваши ♂️fingers♂️ (Right version) Gachi Remix", "path": "Z:/гачибасс/GachiBassRadioV2/Вирус - Ну где же ваши ♂️fingers♂️ (Right version) Gachi Remix.mp3"},
      {"name": "Г♂ASS♂манов - Дождись (Right Version♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Г♂ASS♂манов - Дождись (Right Version♂).mp3"},
      {"name": "Земфира - Сигареты [right version gachi mix]", "path": "Z:/гачибасс/GachiBassRadioV2/Земфира - Сигареты [right version gachi mix].mp3"},
      {"name": "Иг♂рь Ник♂лаев - ♂Пять Причин♂ (Right Version)", "path": "Z:/гачибасс/GachiBassRadioV2/Иг♂рь Ник♂лаев - ♂Пять Причин♂ (Right Version).mp3"},
      {"name": "Кто пчелок уважает - (GachiRemix GachiBass) for Stray228", "path": "Z:/гачибасс/GachiBassRadioV2/Кто пчелок уважает - (GachiRemix GachiBass) for Stray228.mp3"},
      {"name": "Лепс - Я тебя не люблю (right version) G-man", "path": "Z:/гачибасс/GachiBassRadioV2/Лепс - Я тебя не люблю (right version) G-man.mp3"},
      {"name": "Лепс и Аллегрова - Я тебе тебе не верю (right version) G-man", "path": "Z:/гачибасс/GachiBassRadioV2/Лепс и Аллегрова - Я тебе тебе не верю (right version) G-man.mp3"},
      {"name": "НОВЫЙ ГАЧИ ПИРАТ (♂Right version♂) Gachi remix", "path": "Z:/гачибасс/GachiBassRadioV2/НОВЫЙ ГАЧИ ПИРАТ (♂Right version♂) Gachi remix.mp3"},
      {"name": "Нюша - Чудо (right version) G-man", "path": "Z:/гачибасс/GachiBassRadioV2/Нюша - Чудо (right version) G-man.mp3"},
      {"name": "Песенка о медведях (Gachi Version) Гачимучи ремикс", "path": "Z:/гачибасс/GachiBassRadioV2/Песенка о медведях (Gachi Version) Гачимучи ремикс.mp3"},
      {"name": "Руки Вверх - Он тебя ♂Do Anal♂", "path": "Z:/гачибасс/GachiBassRadioV2/Руки Вверх - Он тебя ♂Do Anal♂.mp3"},
      {"name": "Сектор газа - Возле ♂Dungeon♂ твоего", "path": "Z:/гачибасс/GachiBassRadioV2/Сектор газа - Возле ♂Dungeon♂ твоего.mp3"},
      {"name": "Смысловые галлюцинации - Вечно молодой (right version) G-man", "path": "Z:/гачибасс/GachiBassRadioV2/Смысловые галлюцинации - Вечно молодой (right version) G-man.mp3"},
      {"name": "Татьяна Овсиенко - Капитан (Right Version♂)", "path": "Z:/гачибасс/GachiBassRadioV2/Татьяна Овсиенко - Капитан (Right Version♂).mp3"},
      {"name": "Юность в сапогах (Gachi Version) _ Гачимучи ремикс", "path": "Z:/гачибасс/GachiBassRadioV2/Юность в сапогах (Gachi Version) _ Гачимучи ремикс.mp3"},
      {"name": "♂ 2 VANLIMITED - ASS LIMIT ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ 2 VANLIMITED - ASS LIMIT ♂.mp3"},
      {"name": "♂ 21 Pilots - Mad Things ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ 21 Pilots - Mad Things ♂.mp3"},
      {"name": "♂ ABBA ♂ - Give Me a ♂Van♂ After Midnight", "path": "Z:/гачибасс/GachiBassRadioV2/♂ ABBA ♂ - Give Me a ♂Van♂ After Midnight.mp3"},
      {"name": "♂ ANIKI OF THE NIGHT ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ ANIKI OF THE NIGHT ♂.mp3"},
      {"name": "♂ Aaron Smith  - Gachin ♂ [right version ♂] (Aaron Smith - Dancin)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Aaron Smith  - Gachin ♂ [right version ♂] (Aaron Smith - Dancin).mp3"},
      {"name": "♂ Atleast it smells like it ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Atleast it smells like it ♂.mp3"},
      {"name": "♂ Billy 182 - Lets spank your ass forever ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Billy 182 - Lets spank your ass forever ♂.mp3"},
      {"name": "♂ Billy Goulding - Lights ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Billy Goulding - Lights ♂.mp3"},
      {"name": "♂ Blame it on the gachi ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Blame it on the gachi ♂.mp3"},
      {"name": "♂ Bruises ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Bruises ♂.mp3"},
      {"name": "♂ Butterfly (Gachi mix) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Butterfly (Gachi mix) ♂.mp3"},
      {"name": "♂ CHAHANBEATS - DUNGE♂♂♂NLAND ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ CHAHANBEATS - DUNGE♂♂♂NLAND ♂.mp3"},
      {"name": "♂ Call On Me (Right Version) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Call On Me (Right Version) ♂.mp3"},
      {"name": "♂ Caramelldansen ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Caramelldansen ♂.mp3"},
      {"name": "♂ College Boy - Lose Yourass ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ College Boy - Lose Yourass ♂.mp3"},
      {"name": "♂ Deep Dark Evangelion - Cruel Dungeon Master ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Deep Dark Evangelion - Cruel Dungeon Master ♂.mp3"},
      {"name": "♂ Doki Doki Leather Club ♂ [ RIGHT VERSION ]", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Doki Doki Leather Club ♂ [ RIGHT VERSION ].mp3"},
      {"name": "♂ Eminem - Just Lube It ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Eminem - Just Lube It ♂.mp3"},
      {"name": "♂ FUCKED - VI VON BEE CALZONE (FEAT. $300) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ FUCKED - VI VON BEE CALZONE (FEAT. $300) ♂.mp3"},
      {"name": "♂ Feels Harder inc ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Feels Harder inc ♂.mp3"},
      {"name": "♂ Feint Time Bomb ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Feint Time Bomb ♂.mp3"},
      {"name": "♂ Firewatch Palace - Loan Digger ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Firewatch Palace - Loan Digger ♂.mp3"},
      {"name": "♂ Frame of Mind ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Frame of Mind ♂.mp3"},
      {"name": "♂ Fukkireta ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Fukkireta ♂.mp3"},
      {"name": "♂ G.A.C.H.I. ♂ - gachimuchi", "path": "Z:/гачибасс/GachiBassRadioV2/♂ G.A.C.H.I. ♂ - gachimuchi.mp3"},
      {"name": "♂ Gachimuchi ♂ - ♂ Sjow minus Kevin Turtle ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachimuchi ♂ - ♂ Sjow minus Kevin Turtle ♂.mp3"},
      {"name": "♂ Gachophone ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gachophone ♂.mp3"},
      {"name": "♂ Gaynther - Ding Dong Song ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Gaynther - Ding Dong Song ♂.mp3"},
      {"name": "♂ Imagine Dragons - Radioactive ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Imagine Dragons - Radioactive ♂.mp3"},
      {"name": "♂ Initial D ♂ Remember Me ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Initial D ♂ Remember Me ♂.mp3"},
      {"name": "♂ Its raining Van ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Its raining Van ♂.mp3"},
      {"name": "♂ Maroon 5 - Moves Like Aniki ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Maroon 5 - Moves Like Aniki ♂.mp3"},
      {"name": "♂ Masturbator - Sex Squad ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Masturbator - Sex Squad ♂.mp3"},
      {"name": "♂ Max Frost - White Lies ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Max Frost - White Lies ♂.mp3"},
      {"name": "♂ Miracle ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Miracle ♂.mp3"},
      {"name": "♂ Morandi - Angels ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Morandi - Angels ♂.mp3"},
      {"name": "♂ Morrowind - Nerevar Rising♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Morrowind - Nerevar Rising♂.mp3"},
      {"name": "♂ Mr. Sex O Deep ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Mr. Sex O Deep ♂.mp3"},
      {"name": "♂ Over the Whole Entire House ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Over the Whole Entire House ♂.mp3"},
      {"name": "♂ PHOON gachiHop ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ PHOON gachiHop ♂.mp3"},
      {"name": "♂ Performance Artist Podcast Ep. 469 ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Performance Artist Podcast Ep. 469 ♂.mp3"},
      {"name": "♂ Rip the Skin (Evans) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Rip the Skin (Evans) ♂.mp3"},
      {"name": "♂ SUCKWAY - FUCKING SPANKCORE ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ SUCKWAY - FUCKING SPANKCORE ♂.mp3"},
      {"name": "♂ Shape of Your Ass ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Shape of Your Ass ♂.mp3"},
      {"name": "♂ Shooting Gaybars ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Shooting Gaybars ♂.mp3"},
      {"name": "♂ Skrillex - BoyNextDoorang ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Skrillex - BoyNextDoorang ♂.mp3"},
      {"name": "♂ Slave ♂ Shop ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Slave ♂ Shop ♂.mp3"},
      {"name": "♂ THE PRODUNGEON - SPANK MY ASS UP ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ THE PRODUNGEON - SPANK MY ASS UP ♂.mp3"},
      {"name": "♂ THEFATASS - FUCKPOT ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ THEFATASS - FUCKPOT ♂.mp3"},
      {"name": "♂ THUNDERPATRULLEN - TO THE DUNGEON (FT. ANIKI) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ THUNDERPATRULLEN - TO THE DUNGEON (FT. ANIKI) ♂.mp3"},
      {"name": "♂ Takexic ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Takexic ♂.mp3"},
      {"name": "♂ TheFatRat - Time Lapse ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ TheFatRat - Time Lapse ♂.mp3"},
      {"name": "♂ Tobu - Waves ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Tobu - Waves ♂.mp3"},
      {"name": "♂ V4N - DUNGEON POP ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ V4N - DUNGEON POP ♂.mp3"},
      {"name": "♂ VANDUIN _ WOLFGANG BILLY - JIZZY (FT. ANALLA) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VANDUIN _ WOLFGANG BILLY - JIZZY (FT. ANALLA) ♂.mp3"},
      {"name": "♂ VANIS _ LAURA VAN - CUM OVER ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VANIS _ LAURA VAN - CUM OVER ♂.mp3"},
      {"name": "♂ VANRINTH - ASS TIME (GACHI PARTY REMIX) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VANRINTH - ASS TIME (GACHI PARTY REMIX) ♂.mp3"},
      {"name": "♂ VaNksi - Stranger (feat.Billy) ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ VaNksi - Stranger (feat.Billy) ♂.mp3"},
      {"name": "♂ Van No Speak Americano ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Van No Speak Americano ♂.mp3"},
      {"name": "♂ WOLFGANG BILLY _ VANDUIN - ASSPERFECTION ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ WOLFGANG BILLY _ VANDUIN - ASSPERFECTION ♂.mp3"},
      {"name": "♂ Weeaboru next door ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Weeaboru next door ♂.mp3"},
      {"name": "♂ What does the Slave say ♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ What does the Slave say ♂.mp3"},
      {"name": "♂ АЛЬЯНС ♂ – ♂SLAVES♂ НА ЗАРЕ (Gachi remix)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ АЛЬЯНС ♂ – ♂SLAVES♂ НА ЗАРЕ (Gachi remix).mp3"},
      {"name": "♂ Катя Лель - Мой Мармеладный Boss Of This Gym ♂ (Gachi Remix)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Катя Лель - Мой Мармеладный Boss Of This Gym ♂ (Gachi Remix).mp3"},
      {"name": "♂ Френдзона - BOYчик ♂ (Right version)", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Френдзона - BOYчик ♂ (Right version).mp3"},
      {"name": "♂ Aniki Gachi San - Sons of Gachi♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂ Aniki Gachi San - Sons of Gachi♂.mp3"},
      {"name": "♂Dam Daddy Do♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Dam Daddy Do♂.mp3"},
      {"name": "♂Dungeon in the sky♂(experimental gachi)", "path": "Z:/гачибасс/GachiBassRadioV2/♂Dungeon in the sky♂(experimental gachi).mp3"},
      {"name": "♂FACE - Юморист (Right version)♂ _ Gachi remix", "path": "Z:/гачибасс/GachiBassRadioV2/♂FACE - Юморист (Right version)♂ _ Gachi remix.mp3"},
      {"name": "♂Farewell to Gachi♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Farewell to Gachi♂.mp3"},
      {"name": "♂GACHI TWIST♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂GACHI TWIST♂.mp3"},
      {"name": "♂GACHILLMUCHI♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂GACHILLMUCHI♂.mp3"},
      {"name": "♂Gachirune - Cum buster(Battle theme)♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Gachirune - Cum buster(Battle theme)♂.mp3"},
      {"name": "♂Lil Slave X - Old Town Road♂ _ Gachi Remix", "path": "Z:/гачибасс/GachiBassRadioV2/♂Lil Slave X - Old Town Road♂ _ Gachi Remix.mp3"},
      {"name": "♂Quartermaster♂ - ♂GACHI CITY♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Quartermaster♂ - ♂GACHI CITY♂.mp3"},
      {"name": "♂Super Gachi World♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Super Gachi World♂.mp3"},
      {"name": "♂The Witcher 3 Wild Hunt♂ - ♂Cum on the Cobblestones♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂The Witcher 3 Wild Hunt♂ - ♂Cum on the Cobblestones♂.mp3"},
      {"name": "♂Гейфейс♂едет♂suck♂some♂dick♂", "path": "Z:/гачибасс/GachiBassRadioV2/♂Гейфейс♂едет♂suck♂some♂dick♂.mp3"},
      {"name": "♂Дом 2 - 15 Fucking Slaves ♂ (Gachi Remix)", "path": "Z:/гачибасс/GachiBassRadioV2/♂Дом 2 - 15 Fucking Slaves ♂ (Gachi Remix).mp3"},
      {"name": "♂МУККА♂ - ♂ДЕВОЧКА♂С♂ANAL (Gachi Remix)", "path": "Z:/гачибасс/GachiBassRadioV2/♂МУККА♂ - ♂ДЕВОЧКА♂С♂ANAL (Gachi Remix).mp3"},
      {"name": "【Aniki】阿姨压一压 av55295315", "path": "Z:/гачибасс/GachiBassRadioV2/【Aniki】阿姨压一压 av55295315.mp3"},
      {"name": "【Gachimuchi】 - Bilibili ♂ Shanghai", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 - Bilibili ♂ Shanghai.mp3"},
      {"name": "【Gachimuchi】 - Russian Wrestling Festival", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 - Russian Wrestling Festival.mp3"},
      {"name": "【Gachimuchi】 - Spring Time", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 - Spring Time.mp3"},
      {"name": "【Gachimuchi】 Moskau♂", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 Moskau♂.mp3"},
      {"name": "【Gachimuchi】 Remember♂The♂Name", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 Remember♂The♂Name.mp3"},
      {"name": "【Gachimuchi】 This Is What You Came For", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 This Is What You Came For.mp3"},
      {"name": "【Gachimuchi】 We♂are♂electric", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 We♂are♂electric.mp3"},
      {"name": "【Gachimuchi】 Windfall", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 Windfall.mp3"},
      {"name": "【Gachimuchi】 摔♂跤Again（VAN深情演唱）", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】 摔♂跤Again（VAN深情演唱）.mp3"},
      {"name": "【Gachimuchi】Animals♂", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Animals♂.mp3"},
      {"name": "【Gachimuchi】Ass♂ass♂ins Creed", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Ass♂ass♂ins Creed.mp3"},
      {"name": "【Gachimuchi】Beat It♂", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Beat It♂.mp3"},
      {"name": "【Gachimuchi】Black♂Pineapple", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Black♂Pineapple.mp3"},
      {"name": "【Gachimuchi】Closer♂", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Closer♂.mp3"},
      {"name": "【Gachimuchi】Gay ♂ Party ♥", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Gay ♂ Party ♥.mp3"},
      {"name": "【Gachimuchi】Intro - The xx", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Intro - The xx.mp3"},
      {"name": "【Gachimuchi】Just Dance♂", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Just Dance♂.mp3"},
      {"name": "【Gachimuchi】Pacific♂Rim", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Pacific♂Rim.mp3"},
      {"name": "【Gachimuchi】Scream♂shout （抖腿向)", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Scream♂shout （抖腿向).mp3"},
      {"name": "【Gachimuchi】Shotgun♂火", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】Shotgun♂火.mp3"},
      {"name": "【Gachimuchi】World♂Of♂Tanks", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】World♂Of♂Tanks.mp3"},
      {"name": "【Gachimuchi】你听过这么劲♂爆的电音吗？", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】你听过这么劲♂爆的电音吗？.mp3"},
      {"name": "【Gachimuchi】少♂男终末旅行", "path": "Z:/гачибасс/GachiBassRadioV2/【Gachimuchi】少♂男终末旅行.mp3"},
      {"name": "【Non Non Biyori _ Gachimuchi】Highscore", "path": "Z:/гачибасс/GachiBassRadioV2/【Non Non Biyori _ Gachimuchi】Highscore.mp3"},
      {"name": "【Shinnippori Rock】 - Numb♂【NYU-METAL】", "path": "Z:/гачибасс/GachiBassRadioV2/【Shinnippori Rock】 - Numb♂【NYU-METAL】.mp3"},
      {"name": "【Undertale】 - MEGALOVAN様", "path": "Z:/гачибасс/GachiBassRadioV2/【Undertale】 - MEGALOVAN様.mp3"},
      {"name": "【van的rap单曲】the♂deep♂dark 千层面", "path": "Z:/гачибасс/GachiBassRadioV2/【van的rap单曲】the♂deep♂dark 千层面.mp3"},
      {"name": "【兄贵】Mermaid Aniki", "path": "Z:/гачибасс/GachiBassRadioV2/【兄贵】Mermaid Aniki.mp3"},
      {"name": "【哲♂学电音】Hymn♂ For The Weekend Remix—Coldplay Alan♂ Walker", "path": "Z:/гачибасс/GachiBassRadioV2/【哲♂学电音】Hymn♂ For The Weekend Remix—Coldplay Alan♂ Walker.mp3"},
      {"name": "【哲学】Move Your Body 【自由版】", "path": "Z:/гачибасс/GachiBassRadioV2/【哲学】Move Your Body 【自由版】.mp3"},
      {"name": "【哲学】Never Be Alone", "path": "Z:/гачибасс/GachiBassRadioV2/【哲学】Never Be Alone.mp3"},
      {"name": "【哲学】mi♂mi♂mi♂", "path": "Z:/гачибасс/GachiBassRadioV2/【哲学】mi♂mi♂mi♂.mp3"},
      {"name": "〜 OH SHIT IM SORRY 〜 REMIX", "path": "Z:/гачибасс/GachiBassRadioV2/〜 OH SHIT IM SORRY 〜 REMIX.mp3"}
    ]
  }
]
